name = "Ipf"
uuid = "dfb2dbec-0384-47ba-b614-66be42e3cf9e"
authors = ["Andrea Pasquale <andrea.pasquale@polimi.it>"]
version = "1.0.0"

[deps]
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
