name = "IPFFiles"
uuid = "dfb2dbec-0384-47ba-b614-66be42e3cf9e"
authors = ["Andrea Pasquale <andrea.pasquale@polimi.it>"]
version = "0.1.0"

[compat]
julia = "1.0"
PreallocationTools = "0.4"

[deps]
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"

[weakdeps]
CalcephEphemeris = "54e8752a-b65a-4aac-bda5-4918ee1e3cc5"
Ephemerides = "6a9c3322-c8fe-4c26-8ad6-14a6f8acd2a0"
JSMDInterfaces = "6b30ee2f-618e-4a15-bf4e-7df7b496e609"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extensions]
CalcephEphemerisExt = ["CalcephEphemeris", "JSMDInterfaces", "StaticArrays"]
EphemeridesExt = ["Ephemerides", "JSMDInterfaces"]